### ISSUE TITLE
Show the latest article feed on the home page

### ISSUE THREAD

**Issue by arjanvillon** [new-order-network/dao-app-frontend#7]
Currently, the home page contains a hardcoded set of articles from the mirror website. We need to find a way to make this automated or at least dynamic.

**Comment by moonderek** [comment]
I guess it's a matter of querying the mirror.xyz data on arweave. A quick search led me to https://github.com/cjpais/mirror-api.. Unfortunately it looks this repo does not have the ability to search for articles by wallet address (but does allow search by publisher ie: _publisher_name_.mirror.xyz). Not sure if we want to rely on a third party db tho...

One option could be to add search by wallet to the cjpais repo or create our own query https://arweave.net/graphql and parse

Thoughts?

**Comment by arjanvillon** [comment]
Yes. We're currently using the arweave graphql and parse it with arweave package i believe. But we do need to find a way to get the images somewhere. But I think that's already completed as well. Will push a commit soon.

**Comment by moonderek** [comment]
Ah I need to familiarize myself with the repo code. thanks for letting me know
